service: graphql-codepepper

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  timeout: 15
  stage: dev
  region: eu-central-1
  vpc:
    securityGroupIds:
      - sg-c73512bf
    subnetIds:
      - subnet-93a853ef
      - subnet-82139ee8
      - subnet-78a56b34

functions:
  graphqlCharacters:
    handler: dist/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: get
          cors: true

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref" : "IamRoleLambdaExecution"}
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
